name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Java 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

      - name: Verify Java Version
        run: |
          java -version
          javac -version

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build . -t my-node-app

      - name: Run tests
        run: npm test

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonar-scanner

      - name: Check SonarQube Scanner version
        run: sonar-scanner --version

      - name: Set JAVA_HOME and Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          sonar-scanner -X \
            -Dsonar.projectKey=my-node-app \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://9000-port-e1825dfafca340bd.labs.kodekloud.com \
            -Dsonar.login=$SONAR_TOKEN
