name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu as GitHub Actions runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build . -t my-node-app

      - name: Run tests now
        run: npm test

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=my-node-app \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://your-sonarqube-server \
            -Dsonar.login=$SONAR_TOKEN
