name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Java 17
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
          sudo update-alternatives --config java

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build . -t my-node-app

      - name: Run tests
        run: npm test

      - name: Install SonarQube Scanner
        run: npm install -g sonar-scanner

      - name: Check Java version
        run: java -version

      - name: Check SonarQube Scanner version
        run: sonar-scanner --version

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -X \
            -Dsonar.projectKey=my-node-app \
            -Dsonar.sources=src \
            -Dsonar.host.url=https://9000-port-e1825dfafca340bd.labs.kodekloud.com \
            -Dsonar.login=$SONAR_TOKEN
